### ISSUE TITLE
about your problem. 

### ISSUE THREAD

**Issue by crazyofapple** [shenweichen/DSIN#1]
Hi,

The nan problem in training, I have no idea. Can you fix it?  How many epochs is the model converge?

The nan problem in test, you can change the last line with
`print("test LogLoss {0}".format(
        round(log_loss(test_label, np.array(pred_ans, dtype=np.float64), labels=(0, 1)), 4)))`
maybe work.
btw, I wonder if preprocessed pkl will be released. 

Thanks!

**Comment by shenweichen** [comment]
thanks for your advice,1 epoch is enough to converge.
we will release the pkl files later
