### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[6,0] = 9984 is not in [0, 5619)

### ISSUE THREAD

**Issue by jellchou** [shenweichen/DSIN#10]
I ran the train_din.py code, and throw this exception. I have try in two different servers.  Tthe problem took place both in two servers.

**Comment by jellchou** [comment]
I saw the same error [https://github.com/shenweichen/DSIN/issues/8](url), you said that to clone the latest code, and my code was the latest.

**Comment by mengdagegehexiaohuya** [comment]
同样出现了以上问题，解决了一下也没有调出来，求大佬解答

**Comment by Heyi007** [comment]
This error means that embedding table is smaller than sparse feature length, a simplest way is to enlarge the embedding table size, modifying code/models/dsin.py:
`sparse_embedding_dict = {feat.name: Embedding(feat.dimension, embedding_size,...`
to
`sparse_embedding_dict = {feat.name: Embedding(feat.dimension*5, embedding_size,...`
this may affect model performance.

**Comment by shenweichen** [comment]
sorry for this mistake, we are planning to refactor our code in the future.
I think this error can be fixed by using
```python
sparse_feature_list = [SingleFeat(feat, data[feat].max(
    ) + 1) for feat in sparse_features + ['cate_id', 'brand']]
```
instead of 
```python
sparse_feature_list = [SingleFeat(feat, data[feat].nunique(
    ) + 1) for feat in sparse_features + ['cate_id', 'brand']]
```
in 
https://github.com/shenweichen/DSIN/blob/3aed7819e47f0463f12ab78cc2589cacf1081745/code/2_gen_din_input.py#L89

**Comment by btbuwzh** [comment]
我用的是你的最新的代码，其中那两行已经修改过了，还是会这个错误tensorflow.python.framework.errors_impl.InvalidArgumentError
