### ISSUE TITLE
关于代码中Transformer输入格式的疑惑

### ISSUE THREAD

**Issue by juemifuji** [shenweichen/DSIN#12]
你好！我看代码里面Transformer输入是TR([tr_input[i], tr_input[i]])，但是其具体函数定义格式又是：def call(self, inputs, mask=None, training=None, **kwargs)，其中的参数mask，要求是和tr_input[i]同shape或者是(batch_size, 1)，不知道是不是我哪里有遗漏，谢谢！

**Comment by shenweichen** [comment]
输入的时候输入的是一个list作为`inputs`参数传入,mask参数取的是默认值`None`

**Comment by muGithub** [comment]
> 输入的时候输入的是一个list作为`inputs`参数传入,mask参数取的是默认值`None`

你好，如果mask参数取默认值“None”，则会报以下错误：
query_masks, key_masks = mask
    TypeError: 'NoneType' object is not iterable
该如何解决呢？

**Comment by muGithub** [comment]
It's a confirmed letter, I have received your letter, thank you!  addressor: Guo, Youtian
