### ISSUE TITLE
#Parameter is zero for gru and attention layer?

### ISSUE THREAD

**Issue by arsenezhang** [shenweichen/DSIN#13]
Hello, I am running you baseline train_dien.py
add 
`    names = [weight.name for layer in model.layers for weight in layer.weights]
    weights = model.get_weights()

    for name, weight in zip(names, weights):
        print(name, weight.shape)`
to print variable in model and get
<img width="287" alt="屏幕快照 2019-12-13 下午4 12 26" src="https://user-images.githubusercontent.com/51918820/70783606-c3430900-1dc3-11ea-9642-8a1262947b1a.png">
why there is no parameter for gru and attention layer? I user model.summary() also show no parameter for these two layer.

**Comment by shenweichen** [comment]
hi, some parameters are not included,this is due to the keras summary calculation logic.

**Comment by arsenezhang** [comment]
> hi, some parameters are not included,this is due to the keras summary calculation logic.

thanks for reply. so the parameters in gru and attention layer is trained or not ?

**Comment by shenweichen** [comment]
They are all trained

**Comment by arsenezhang** [comment]
> They are all trained

OK, thanks~
