### ISSUE TITLE
Transformer类中call()的问题

### ISSUE THREAD

**Issue by mengqide21** [shenweichen/DSIN#16]
在deepctr库的Transformer类中有：
    def call(self, inputs, mask=None, training=None, **kwargs):
        if self.supports_masking:
            queries, keys = inputs
            query_masks, key_masks = mask
            print('query_masks:',query_masks.get_shape())
            query_masks = tf.cast(query_masks, tf.float32)
            key_masks = tf.cast(key_masks, tf.float32)
我在复现DSIN的时候，如果是保持原配置不变的话复现是没有问题的。但是实际上我在将原输入划分成两个序列长为5的序列分别输入时，在执行query_masks, key_masks = mask这一步时就会提示'Nonetype' is not iterable。

python version [3.6]
tensorflow version [1.4.0]
deepctr version [0.4.1]

**Comment by shenweichen** [comment]
请提供一份利用demo数据的可复现该问题的完整代码～ 发到邮箱wcshen1994@163.com 谢谢

**Comment by mengqide21** [comment]
> 请提供一份利用demo数据的可复现该问题的完整代码～ 发到邮箱[wcshen1994@163.com](mailto:wcshen1994@163.com) 谢谢

已发，谢谢

**Comment by muGithub** [comment]
> 在deepctr库的Transformer类中有：
> def call(self, inputs, mask=None, training=None, **kwargs):
> if self.supports_masking:
> queries, keys = inputs
> query_masks, key_masks = mask
> print('query_masks:',query_masks.get_shape())
> query_masks = tf.cast(query_masks, tf.float32)
> key_masks = tf.cast(key_masks, tf.float32)
> 我在复现DSIN的时候，如果是保持原配置不变的话复现是没有问题的。但是实际上我在将原输入划分成两个序列长为5的序列分别输入时，在执行query_masks, key_masks = mask这一步时就会提示'Nonetype' is not iterable。
> 
> python version [3.6]
> tensorflow version [1.4.0]
> deepctr version [0.4.1]

哈喽，你的问题解决了吗，我也遇到了同样的问题
