### ISSUE TITLE
如何使用线上数据预测

### ISSUE THREAD

**Issue by huangxianliang** [shenweichen/DSIN#18]
hi，DSIN非常棒，还有测试数据，想请教个问题，模型训练后怎么对线上数据进行预测，模型预测是否click，预测数据需要如何组装

**Comment by 649435349** [comment]
什么叫对线上数据进行预测？如果是线上服务的话，这个感觉是工业问题吧，每个公司都会有成熟的在线 inference 系统的，具体得问问你们的工程实现方啊。在线预测的时候，输入的组织方式和离线的是一致的。

**Comment by huangxianliang** [comment]
> 什么叫对线上数据进行预测？如果是线上服务的话，这个感觉是工业问题吧，每个公司都会有成熟的在线 inference 系统的，具体得问问你们的工程实现方啊。在线预测的时候，输入的组织方式和离线的是一致的。

可能没有描述清楚，问题是这样的：离线训练的时候，用的是user_feat + ad_feat + session_list数据，预测是否点击，线上如果也这样的话应该没有意义了吧，因为session_list既然都已经发生了，预测是否点击也就没意义了，还请赐教

**Comment by 649435349** [comment]
额，你好像对 CTR 问题不是很理解，你可以看看我引用的 DIN / YoutubeNet 那篇论文，里面有工程介绍。

**Comment by JWenBin** [comment]
直接按照训练时候的样子组织数据传给模型预测分数不就好了吗？不过可以问下PB格式模型无法导出来咋搞
