### ISSUE TITLE
ImportError: No module named input_embedding in package DeepCTR

### ISSUE THREAD

**Issue by wenruij** [shenweichen/DSIN#3]
`ImportError: No module named input_embedding` when `from deepctr.input_embedding import create_singlefeat_inputdict` (`master/code/models/dsin.py`)

`pip install deepctr` has been done！

python version: Python 2.7.10

**Comment by shenweichen** [comment]
please use `pip install deepctr==0.4.1`

**Comment by wenruij** [comment]
Thanks, that works.
