### ISSUE TITLE
The code file "train_dsin.py" fails to run.

### ISSUE THREAD

**Issue by Cobuild427** [shenweichen/DSIN#4]
Hi,
I have set up the enviroment and generated the input data for the DSIN model following the instruction. But I still failed to the train the model executing "train_dsin.py". The error messages are in the attachment. 
Thank you for your time!
![issue](https://user-images.githubusercontent.com/1689235/61263084-3ff09d80-a7ba-11e9-9a1c-1b8ab3f804b9.png)

**Comment by Cobuild427** [comment]
I revised the 152-th line in "2_gen_dsin_input.py", 
sess_input_dict[sess_name][feat], maxlen=SESS_COUNT, padding='post'))
I have changed maxlen=SESS_COUNT to maxlen=DSIN_SESS_MAX_LEN, the previous bug was fixed, but here comes another error:

![issue2](https://user-images.githubusercontent.com/1689235/61279895-8f9a8d80-a7e9-11e9-95a5-f42ad6af034c.png)

**Comment by shenweichen** [comment]
hi @Cobuild427 ,sorry for the mistake of `DSIN_SESS_MAX_LEN `.
The Error of `GPU Sync failed`  seems to be caused by the  environment，you can google it and search for some solutions .
