### ISSUE TITLE
关于序列构造的问题

### ISSUE THREAD

**Issue by caojiajia** [shenweichen/DSIN#6]
你好，请问一下，论文中只是使用了用户的点击序列，那么用户的收藏序列或者购买序列是否也能加进去？如果多个序列的话应该是不能共享参数的？

**Comment by 649435349** [comment]
我们尝试过其他序列的建模，都是负向效果。我们不确定如果一个用户买过XX,是不是应该给他再推类似的东西? 收藏的话过于稀疏了，也不好用。
PS 你可以看看ATRANK 是专门做 heterogenous sequence rank 的。

**Comment by caojiajia** [comment]
好的，多谢哈，我去看看
