### ISSUE TITLE
run train_din error

### ISSUE THREAD

**Issue by blldd** [shenweichen/DSIN#7]
hi, very lucky to study your work! And I have some questions about your code:
My TF version is 1.13.0 , cuda 10.0, I got :
    AttributeError: 'Tensor' object has no attribute '_uses_learning_phase'
error like this.

So I pip install tf 1.4.0 according to your readme, and got :
ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory
Seems like my cuda version cannot work with tf version, So do you know how to fix this case?

Thank you for your time !

**Comment by shenweichen** [comment]
hi ,tf1.4.0-gpu must run on CUDA 8 and  your is CUDA10
