### ISSUE TITLE
0_gen_sampled_data.py error

### ISSUE THREAD

**Issue by q710245300** [shenweichen/DSIN#9]
Hi, I have got an error while run 0_gen_sampled_data.py, the info as follows:
![图片](https://user-images.githubusercontent.com/29564485/65568235-9d0f8900-df8b-11e9-8471-482aff7b0a23.png)
My computer memory is 8GB.Do you know how to fix this, thanks!

**Comment by shenweichen** [comment]
try read the data in batch mode
